apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ztdns.fullname" . }}
  labels:
    {{- include "ztdns.labels" . | nindent 4 }}
type: Opaque
stringData:
  ZEROTIER_TOKEN: {{ .Values.zerotier.apiToken }}
